runtime: go111
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 100

inbound_services:
- mail

handlers:
- url: /_reap-inactive-waiting-players
  script: auto
  login: admin
- url: /_ah/queue/go/delay
  script: auto
  login: admin
- url: /(favicon.ico)
  static_files: app/img/\1
  upload: app/img/.*
- url: /(firebase-messaging-sw.js)
  static_files: app/js/\1
  upload: app/js/.*
- url: /(html|js|css|img)/(.*)
  static_files: app/\1/\2
  upload: app/(html|js|css|img)/(.*)
- url: /.*
  script: auto
  secure: always
