runtime: go111
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 100

inbound_services:
- mail

handlers:
- url: /_reap-inactive-waiting-players
  script: auto
  login: admin
- url: /(favicon.ico)
  static_files: img/\1
  upload: img/favicon.ico
- url: /(firebase-messaging-sw.js)
  static_files: js/\1
  upload: js/firebase-messaging-sw.js
- url: /html
  static_dir: html
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /.*
  script: auto
  secure: always
