runtime: go111
automatic_scaling:
  max_idle_instances: 1
  max_concurrent_requests: 100

inbound_services:
- mail

handlers:
- url: /_reap-inactive-waiting-players
  script: auto
  login: admin
- url: /(favicon.ico)
  static_files: img/\1
  upload: app/img/favicon.ico
- url: /(firebase-messaging-sw.js)
  static_files: js/\1
  upload: app/js/firebase-messaging-sw.js
- url: /html
  static_dir: app/html
- url: /js
  static_dir: app/js
- url: /css
  static_dir: app/css
- url: /img
  static_dir: app/img
- url: /.*
  script: auto
  secure: always
